<nav class="sidenav">
    <div class="main-sidenav">
        <div class="logo-sidenav mb-4">
        </div>
        <div class="wrapper-links-sidenav gap-3 d-flex flex-column">

            <a href="<?php echo $url;?>home" class="link-sidenav" id="cms-link-aside-grupos-comerciais">
                <i class="fa-solid fa-house"></i> Grupos Comerciais
            </a>


            <a href="<?php echo $url;?>login" class="link-sidenav text-danger">
                <i class="fa-solid fa-right-from-bracket"></i> Sair
            </a>
            <a class="link-sidenav">
                <small class="text-muted">Versão: <?php echo $version;?></small>
            </a>


        </div>
    </div>
</nav>
<div class="sidenav-overlay"></div>