<nav class="sidenav">
    <div class="main-sidenav">
        <div class="logo-sidenav mb-4">
            <a href="<?php echo $url;?>">
                <img class="w-100" src="<?php echo $url?>img/logo-colorido.png" alt="">
            </a>
        </div>
        <div class="wrapper-links-sidenav gap-3 d-flex flex-column">

            <a href="<?php echo $url;?>home" class="link-sidenav" id="cms-link-aside-home">
                <i class="fa-solid fa-house"></i> Home
            </a>

            <a href="<?php echo $url;?>servicos/historico-disparos" class="link-sidenav" id="cms-link-aside-historico-disparos">
                <i class="fa-solid fa-list"></i> Histórico de disparos
            </a>

            <a href="<?php echo $url;?>servicos/disparos" class="link-sidenav" id="cms-link-aside-disparos">
                <i class="fa-solid fa-paper-plane"></i> Disparo em massa
            </a>

            <a href="<?php echo $url;?>servicos/disparo-unico" class="link-sidenav" id="cms-link-aside-disparo-unico">
                <i class="fa-solid fa-envelope"></i> Disparo único
            </a>
            <a  href="#" class="link-sidenav placeholder-default" id="cms-link-aside-auto-conversa ">
                <i class="fa-solid fa-robot"></i> Automações de conversa
            </a>


            <a href="<?php echo $url;?>login" class="link-sidenav text-danger">
                <i class="fa-solid fa-right-from-bracket"></i> Sair
            </a>


        </div>
    </div>
</nav>
<div class="sidenav-overlay"></div>